### ISSUE TITLE
Go module in subdirectory seems to confuse GoSec

### ISSUE THREAD

**Issue by safaci2000** [securego/gosec#1067]
### Summary 
Go module is subdirectory seems to confuse gosec. If I'm doing something wrong please call me out on it, but I believe this is a pretty common pattern.

### Steps to reproduce the behavior
My project is laid out as follows.

The 'root' module is defined as: gitlab.es.net/ht/ht-svc-node/
while the grpc_server folder is a module with it's own go.mod, go.sum etc. and defined as:
gitlab.es.net/ht/ht-svc-node/grpc_server/

```
/
/go.mod
/go.sum
/main.go 
/internal/{services,repository,etc}
/grpc_server/
                      service.go
                      go.mod
                      go.sum
/grpc_server/cmd/
                              main.go
/grpc_server/pb/
```

Results:
Golang errors in file: [/builds/ydDAHRpi/0/ht/ht-svc-node/grpc_server/cmd/main.go]:
  > [line 7 : column 2] - could not import gitlab.es.net/ht/ht-svc-node/grpc_server (invalid package name: "")
  > [line 8 : column 2] - could not import gitlab.es.net/ht/ht-svc-node/grpc_server/pb (invalid package name: "")
Golang errors in file: [/builds/ydDAHRpi/0/ht/ht-svc-node/grpc_server/service.go]:
  > [line 10 : column 2] - could not import gitlab.es.net/ht/ht-svc-node/grpc_server/pb (invalid package name: "")

I'm not sure why any of this would affect it but in case it's relevant.
protoc --versioin
libprotoc 24.4   (This is on my local laptop, now we're on OS X)

Portion of my taskfile that installs various tools.

```yaml
version: "3"

vars:
  GRPC_CODE: "proto/api"
  GRPC_VENDOR: "proto/vendor"
  GRPC_PKG: "grpc_client"
  GRPC_API: "{{ .GRPC_CODE}}/sn_p4_v1.proto"
  BIN_NAME: svc-node
  PROTOC_VERSION: "v22.3"
  PROTO_GEN: "v1.31"
  PROTO_GEN_GO: "v1.3"
  SWAG_VERSION: "v1.16.2"
  OS: { sh: uname }

tasks:
   init_protoc:
    desc: "Install protobuf Dependencies"
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@{{ .SWAG_VERSION }}
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@{{ .PROTO_GEN}}
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@{{ .PROTO_GEN_GO }}
      - cd proto; ./fetch.sh 
  build_grpc:
    desc: "build grpc client"
    deps: ["clean"]
    cmds:
      - echo "Building client Code"
      - protoc -I={{ .GRPC_CODE }} -I={{ .GRPC_VENDOR }} --go_out=. --go_opt=Msn_p4_v1.proto=./grpc_client  --go-grpc_out=. --go-grpc_opt=Msn_p4_v1.proto=./grpc_client {{ .GRPC_API}}
      - echo "Building Server Code"
      - protoc -I {{ .GRPC_CODE }} -I={{ .GRPC_VENDOR }} --go_out=grpc_server --go_opt=Msn_p4_v1.proto=./pb  --go-grpc_out=grpc_server --go-grpc_opt=Msn_p4_v1.proto=./pb  proto/api/sn_p4_v1.proto
```
Summary:

### Go version (output of 'go version')
Go 21.4

### Operating system / Environment
Running in Gitlab CICD based on,  golang:alpine 

```yaml
variables:
  security_exclude: G402,G304

SecurityScan:
  stage: validate
  image: golang:alpine
  script:
    - echo "Creating netrc login for gitlab"
    - printf "machine gitlab.es.net\n\
      login ${BUILD_GIT_USER}\n\
      password ${BUILD_SECRET}\n"\
      >> /root/.netrc
    - apk update
    - apk add g++ git
    - go install github.com/securego/gosec/v2/cmd/gosec@latest
    - gosec --exclude=$security_exclude  ./...
  only:
    - push
    - merge_requests

```
### Expected behavior
Security scan to pass, or point out security issues in the code.  Inability to import module is not expected:
### Actual behavior

```
[gosec] 2023/11/08 17:43:53 Checking file: /builds/ydDAHRpi/0/ht/ht-svc-node/main.go
[gosec] 2023/11/08 17:43:53 Checking package: grpc_server
[gosec] 2023/11/08 17:43:53 Checking file: /builds/ydDAHRpi/0/ht/ht-svc-node/grpc_server/service.go
[gosec] 2023/11/08 17:43:53 Panic when running SSA analyser on package: grpc_server
[gosec] 2023/11/08 17:43:53 Error building the SSA representation of the package "grpc_server": %!s(<nil>)
Results:
Golang errors in file: [/builds/ydDAHRpi/0/ht/ht-svc-node/grpc_server/cmd/main.go]:
  > [line 7 : column 2] - could not import gitlab.es.net/ht/ht-svc-node/grpc_server (invalid package name: "")
  > [line 8 : column 2] - could not import gitlab.es.net/ht/ht-svc-node/grpc_server/pb (invalid package name: "")
Golang errors in file: [/builds/ydDAHRpi/0/ht/ht-svc-node/grpc_server/service.go]:
  > [line 10 : column 2] - could not import gitlab.es.net/ht/ht-svc-node/grpc_server/pb (invalid package name: "")
Summary:
  Gosec  : dev
  Files  : 18
  Lines  : 3662
  Nosec  : 0
  Issues : 0
```
