### ISSUE TITLE
Create Actions PR Mode

### ISSUE THREAD

**Issue by darrenvechain** [securego/gosec#1092]
### Summary 

I want like to be able run `gosec` in a PR mode, such that only changes are checked and not the entire repo. With this, existing errors won't fail new PRs, if new PR's changes pass the check

### Steps to reproduce the behavior

golangci allows us to do this by passing `only-new-issues: true`

```yaml
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          only-new-issues: true
```

### gosec version

N/A

### Go version (output of 'go version')

N/A

### Operating system / Environment

N/A

### Expected behavior

```yaml
  gosec:
    name: gosec-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
          pr-mode: true
```

### Actual behavior

The action runs against the entire repo
