### ISSUE TITLE
Go version issues when running in CI (Github Actions)

### ISSUE THREAD

**Issue by saurori** [securego/gosec#1166]
### Summary 

I'm running into a version mismatch when running gosec in Github Actions. I have a dependency [ariga.io/atlas v0.25.0](https://github.com/ariga/atlas/blob/23e5130d5eddbdb31f90c4a3e50f256b701c59d6/go.mod#L3) which is forcing my `go.mod` file to specify the Go version as `go 1.22.5`. It appear the Docker image `securego/gosec:2.20.0` was built iwth [go 1.22.3](https://hub.docker.com/layers/securego/gosec/2.20.0/images/sha256-1b2c61f3a4832d7f464656523a44813f01b0124a517c23ec1ca82dce4a3f399d?context=explore). This results in my CI action failing with errors such as:

```cosole
Golang errors in file: [cmd]:

  > [line 0 : column 0] - loading files from package "cmd": err: exit status 1: stderr: go: go.mod requires go >= 1.22.5 (running go 1.22.3; GOTOOLCHAIN=local)
```

I'm not sure if there is a workaround or if a new Docker image could be built with the latest Go version.

### Steps to reproduce the behavior

Use Github Action (setup-go may not be needed):
```yaml
jobs:
  gosec:
    name: Gosec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-exclude=G108,G203 -exclude-generated ./...'
```

### gosec version

`2.20.0`

### Go version (output of 'go version')

`go version go1.22.5 linux/amd64`
