### ISSUE TITLE
how to run gosec with config files

### ISSUE THREAD

**Issue by Rosyya** [securego/gosec#1322]
when using json file with content:
```
{
    "exclude": "G103, G104"
}
```
G103,G104 still in error report;

when using yaml file:
```
include:
  - "**/*.go"
exclude:
  - "vendor/**"
rules:
  G101: true
  G102: true
  G201: true
```
get error invalid character 'i' in numeric literal
