### ISSUE TITLE
Want to have a base directory concept where I can choose my root directory

### ISSUE THREAD

**Issue by soham308** [securego/gosec#468]
### Summary 

Want to have a base directory concept where I can choose my root directory

### gosec version

go 1.13 and above

**Comment by ccojocar** [comment]
Thanks for reporting this. Can you please provide some more details? You can provide the folder to scan when running the `gosec` tool like this:

```
gosec root-dir/...
```

**Comment by soham308** [comment]
> Thanks for reporting this. Can you please provide some more details? You can provide the folder to scan when running the `gosec` tool like this:
> 
> ```
> gosec root-dir/...
> ```

I am planning to use your actions

```  shell
  - name: Checkout Source 
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
```

But my code is in a directory called my-custom-directory. So I am expecting something like 

```  shell
  - name: Checkout Source 
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
          projectBaseDir: my-custom-directory
```

similar to https://github.com/SonarSource/sonarcloud-github-action/blob/master/README.md

**Comment by ccojocar** [comment]
Have you tried to use the action like:

```
 - name: Checkout Source 
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: my-custom-directory/...
```
 This should work  when the `my-custom-directory` folder is in the root of your git repository.

**Comment by soham308** [comment]
> Have you tried to use the action like:
> 
> ```
>  - name: Checkout Source 
>         uses: actions/checkout@v2
>       - name: Run Gosec Security Scanner
>         uses: securego/gosec@master
>         with:
>           args: my-custom-directory/...
> ```
> 
> This should work when the `my-custom-directory` folder is in the root of your git repository.

I have tried something like this but got some error. let check again and get back to you.

**Comment by ccojocar** [comment]
@soham308 Can we close this issue? Thanks

**Comment by soham308** [comment]
> @soham308 Can we close this issue? Thanks

It's not working actually. I tried giving that one but it didn't work

**Comment by ccojocar** [comment]
What was the output? Can you please provide the structure of you project including the go.mod file in order to understand what's actually the issue? Thanks

**Comment by soham308** [comment]
> What was the output? Can you please provide the structure of you project including the go.mod files in order to understand what's actually the issue (e.g. where are the go.mod file defined in the folder)? Thanks

The structure is like
```
  source  #in root folder
     go   #go codes seat here in go folder under the source folder
  go.mod  #in root folder

```
**Error**

```
dir: /github/workspace
stdout: <<>>
stderr: <<go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.13.10/x64
```

**Comment by ccojocar** [comment]
So this doesn't quite follow the Go layout standard (see this for more details https://golang.org/doc/code.html).

If you structure you code like this, the `root folder` is a module (because you placed the go.mod file in there), and the `go` folder where you have the code is just a package. Either you move the `go.mod` into your `go` folder or you setup separate repositories instead of a monorepo. 

Also some more details here https://github.com/golang-standards/project-layout

**Comment by ccojocar** [comment]
BTW you can find a complete example of a CI flow in this file https://github.com/ccojocar/go-with-github-workflow/blob/master/.github/workflows/ci.yml which works for me.

**Comment by soham308** [comment]
> So this doesn't quite follow the Go layout standard (see this for more details https://golang.org/doc/code.html).
> 
> If you structure you code like this, the `root folder` is a module (because you placed the go.mod file in there), and the `go` folder where you have the code is just a package. Either you move the `go.mod` into your `go` folder or you setup separate repositories instead of a monorepo.
> 
> Also some more details here https://github.com/golang-standards/project-layout

So this may not work is it?


```
 - name: Checkout Source 
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: source/go/...

```

but will this work??
```
 - name: Checkout Source 
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: source/...

```

**Comment by ccojocar** [comment]
The former should work. Did you try it?

**Comment by ccojocar** [comment]
@soham308 Closing this for now. Fee free to reopen it with more context in case still is an issue for you after following the Go standard project layout. Thanks

**Comment by daemon1024** [comment]
Hello, Wanted to bump this concern. 

I provided the base directory as mentioned in the discussion. But I am getting some errors related to import.

I believe it's discussed already and can be solved by providing the -w flag as documented at https://github.com/securego/gosec#docker-image

I was wondering if we could provide an input flag in the action to set -w flag. 

Thank You.

**Comment by ccojocar** [comment]
@daemon1024 Did you try to set up the working directory in your workflow calling the gosec action? Here is a thread related to this https://github.community/t/use-working-directory-for-entire-job/16747/2

Does  imports work with `go build` command?

**Comment by daemon1024** [comment]
@ccojocar as mentioned in the thread 
`working-directory` can't be used with `uses`

I set up a workaround by doing this 
```yaml
 - name: Run Gosec Security Scanner
        run: |
          go get -u github.com/securego/gosec/v2/cmd/gosec
          gosec ./...
        working-directory: KubeArmor

```
