### ISSUE TITLE
gosec as gtihub action: cannot find GOROOT directory:

### ISSUE THREAD

**Issue by cblomart** [securego/gosec#776]
### Summary 

Fail to run in github actions

### Steps to reproduce the behavior

Setup a workflow and include a job for gosec

```yaml
name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  check:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v2

    - name: lint
      uses: golangci/golangci-lint-action@v2

    - name: security
      uses: securego/gosec@master
      with:
        args: ./...
```

### gosec version

v2.9.6

### Go version (output of 'go version')

1.17

### Operating system / Environment

linux debian (github aciton)

### Expected behavior

Have the security analysed

### Actual behavior

```
Golang errors in file: [.]:

  > [line 0 : column 0] - loading files from package ".": err: exit status 2: stderr: go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.17.6/x64
```

**Comment by ccojocar** [comment]
Our scan using the gosec action looks good. You can see that it was executed yesterday https://github.com/securego/gosec/runs/5090860584?check_suite_focus=true. You can find the action defined in this file https://github.com/securego/gosec/blob/master/.github/workflows/scan.yml. 

It might be something related to your project. Are you able to run locally the gosec command?

**Comment by cblomart** [comment]
Thanks, i've reused the workflow definition provided and it does work correctly. 
I am ok with that altought i don't get why.

**Comment by scottmcmaster** [comment]
I'm not sure if this helps anyone, but I've noticed in our Github Action, GOROOT is being passed from the action environment to the container with -e (I haven't been able to figure out what is putting it in the global env, exactly...), and that seems to cause this kind of breakage.

**Comment by rafaelespinoza** [comment]
To others who may have this issue, here's something that worked for my project. This may not work for everybody.

I had an error similar to:
```
Golang errors in file: [.]:

  > [line 0 : column 0] - loading files from package ".": err: exit status 2: stderr: go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.17.7/x64`
```



The `GOROOT` env var needs some attention. Some options:
- Move the security scan step *before* another step with an action that provides a `GOROOT` env var (`actions/setup-go` sets the env var). Editorial note: introducing an ordering dependency isn't very robust.
- Move the security scan into its own job altogether without an action that sets the `GOROOT` env var.
- Set the `GOROOT` env var to `''` just for the security scan step.

Sample workflow file that had errors mentioned above:
```yaml
name: build
on: [push]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...
```
