### ISSUE TITLE
No Documentation Explaining the no-fail flag being used

### ISSUE THREAD

**Issue by OhZedTee** [securego/gosec#785]
### Summary 
The README lists a flag -no-fail being used with gosec that is not documented anywhere.

```
name: "Security Scan"

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every at 00:00 on Sunday UTC time.
on:
  push:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: '-no-fail -fmt sarif -out results.sarif ./...' #HERE
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
```
https://github.com/securego/gosec#integrating-with-code-scanning

Can we please add a sentence or 2 to the docs explaining what this flag does?
