### ISSUE TITLE
Support pinning `gosec` versions through Github Actions

### ISSUE THREAD

**Issue by mwolfe-arkose** [securego/gosec#926]
Due to https://github.com/securego/gosec/issues/925 (and also because it's industry best practice), I'd like to pin `gosec` to a particular version in my Github Actions workflows. Currently, I have a workflow step resembling the following, as recommended by the `README`:

```yaml
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
```

I assumed it would be possible to always use a certain `gosec` version by changing the repository tag, like so:

```yaml
      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.14.0
        with:
          args: ./...
```

However, this doesn't work, since the Github Actions `action.yml` file is set up to always use the latest image on Docker Hub.

Current CI best practices include pinning versions of tools and dependencies to ensure consistent results - i.e. the ideal is that the same CI pipeline, run against the same commit, will produce the same results. This appears to be impossible to achieve using the `gosec` Github Actions step.
